import { z } from 'zod';
export declare const AgentConfigSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    autonomyLevel: z.ZodEnum<["full", "guided", "strict"]>;
    llmModel: z.ZodDefault<z.ZodString>;
    llmFallback: z.ZodDefault<z.ZodString>;
    maxLlmCallsPerHour: z.ZodDefault<z.ZodNumber>;
    chain: z.ZodDefault<z.ZodLiteral<"base">>;
    dexes: z.ZodDefault<z.ZodArray<z.ZodEnum<["aerodrome", "uniswap-v3"]>, "many">>;
    pairs: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    paperBalance: z.ZodDefault<z.ZodNumber>;
    maxPositionSizePct: z.ZodDefault<z.ZodNumber>;
    maxOpenPositions: z.ZodDefault<z.ZodNumber>;
    stopLossPct: z.ZodDefault<z.ZodNumber>;
    takeProfitPct: z.ZodDefault<z.ZodNumber>;
    slippageSimulation: z.ZodDefault<z.ZodNumber>;
    analysisInterval: z.ZodDefault<z.ZodEnum<["1m", "5m", "15m", "1h", "4h", "1d"]>>;
    strategies: z.ZodDefault<z.ZodArray<z.ZodEnum<["ema_crossover", "rsi_oversold", "macd_signal", "bollinger_bounce", "volume_breakout", "llm_sentiment", "combined"]>, "many">>;
    maxDailyLossPct: z.ZodDefault<z.ZodNumber>;
    cooldownAfterLossMinutes: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    name: string;
    autonomyLevel: "full" | "guided" | "strict";
    llmModel: string;
    pairs: string[];
    llmFallback: string;
    maxLlmCallsPerHour: number;
    chain: "base";
    dexes: ("aerodrome" | "uniswap-v3")[];
    paperBalance: number;
    maxPositionSizePct: number;
    maxOpenPositions: number;
    stopLossPct: number;
    takeProfitPct: number;
    slippageSimulation: number;
    analysisInterval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
    strategies: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[];
    maxDailyLossPct: number;
    cooldownAfterLossMinutes: number;
    description?: string | undefined;
}, {
    name: string;
    autonomyLevel: "full" | "guided" | "strict";
    llmModel?: string | undefined;
    pairs?: string[] | undefined;
    description?: string | undefined;
    llmFallback?: string | undefined;
    maxLlmCallsPerHour?: number | undefined;
    chain?: "base" | undefined;
    dexes?: ("aerodrome" | "uniswap-v3")[] | undefined;
    paperBalance?: number | undefined;
    maxPositionSizePct?: number | undefined;
    maxOpenPositions?: number | undefined;
    stopLossPct?: number | undefined;
    takeProfitPct?: number | undefined;
    slippageSimulation?: number | undefined;
    analysisInterval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | undefined;
    strategies?: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[] | undefined;
    maxDailyLossPct?: number | undefined;
    cooldownAfterLossMinutes?: number | undefined;
}>;
export type AgentConfigInput = z.input<typeof AgentConfigSchema>;
export type AgentConfigOutput = z.output<typeof AgentConfigSchema>;
export declare const TradeDecisionSchema: z.ZodObject<{
    action: z.ZodEnum<["buy", "sell", "hold", "close"]>;
    confidence: z.ZodNumber;
    reasoning: z.ZodString;
    targetPair: z.ZodOptional<z.ZodString>;
    suggestedPositionSizePct: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    reasoning: string;
    confidence: number;
    action: "buy" | "sell" | "hold" | "close";
    targetPair?: string | undefined;
    suggestedPositionSizePct?: number | undefined;
}, {
    reasoning: string;
    confidence: number;
    action: "buy" | "sell" | "hold" | "close";
    targetPair?: string | undefined;
    suggestedPositionSizePct?: number | undefined;
}>;
export declare const CreateAgentRequestSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    autonomyLevel: z.ZodDefault<z.ZodEnum<["full", "guided", "strict"]>>;
    llmModel: z.ZodDefault<z.ZodString>;
    llmFallback: z.ZodDefault<z.ZodString>;
    maxLlmCallsPerHour: z.ZodDefault<z.ZodNumber>;
    chain: z.ZodDefault<z.ZodLiteral<"base">>;
    dexes: z.ZodDefault<z.ZodArray<z.ZodEnum<["aerodrome", "uniswap-v3"]>, "many">>;
    pairs: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    paperBalance: z.ZodDefault<z.ZodNumber>;
    maxPositionSizePct: z.ZodDefault<z.ZodNumber>;
    maxOpenPositions: z.ZodDefault<z.ZodNumber>;
    stopLossPct: z.ZodDefault<z.ZodNumber>;
    takeProfitPct: z.ZodDefault<z.ZodNumber>;
    slippageSimulation: z.ZodDefault<z.ZodNumber>;
    analysisInterval: z.ZodDefault<z.ZodEnum<["1m", "5m", "15m", "1h", "4h", "1d"]>>;
    strategies: z.ZodDefault<z.ZodArray<z.ZodEnum<["ema_crossover", "rsi_oversold", "macd_signal", "bollinger_bounce", "volume_breakout", "llm_sentiment", "combined"]>, "many">>;
    maxDailyLossPct: z.ZodDefault<z.ZodNumber>;
    cooldownAfterLossMinutes: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    name: string;
    autonomyLevel: "full" | "guided" | "strict";
    llmModel: string;
    pairs: string[];
    llmFallback: string;
    maxLlmCallsPerHour: number;
    chain: "base";
    dexes: ("aerodrome" | "uniswap-v3")[];
    paperBalance: number;
    maxPositionSizePct: number;
    maxOpenPositions: number;
    stopLossPct: number;
    takeProfitPct: number;
    slippageSimulation: number;
    analysisInterval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
    strategies: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[];
    maxDailyLossPct: number;
    cooldownAfterLossMinutes: number;
    description?: string | undefined;
}, {
    name: string;
    autonomyLevel?: "full" | "guided" | "strict" | undefined;
    llmModel?: string | undefined;
    pairs?: string[] | undefined;
    description?: string | undefined;
    llmFallback?: string | undefined;
    maxLlmCallsPerHour?: number | undefined;
    chain?: "base" | undefined;
    dexes?: ("aerodrome" | "uniswap-v3")[] | undefined;
    paperBalance?: number | undefined;
    maxPositionSizePct?: number | undefined;
    maxOpenPositions?: number | undefined;
    stopLossPct?: number | undefined;
    takeProfitPct?: number | undefined;
    slippageSimulation?: number | undefined;
    analysisInterval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | undefined;
    strategies?: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[] | undefined;
    maxDailyLossPct?: number | undefined;
    cooldownAfterLossMinutes?: number | undefined;
}>;
export declare const UpdateAgentRequestSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    autonomyLevel: z.ZodOptional<z.ZodDefault<z.ZodEnum<["full", "guided", "strict"]>>>;
    llmModel: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    llmFallback: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    maxLlmCallsPerHour: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    chain: z.ZodOptional<z.ZodDefault<z.ZodLiteral<"base">>>;
    dexes: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodEnum<["aerodrome", "uniswap-v3"]>, "many">>>;
    pairs: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    paperBalance: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    maxPositionSizePct: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    maxOpenPositions: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    stopLossPct: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    takeProfitPct: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    slippageSimulation: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    analysisInterval: z.ZodOptional<z.ZodDefault<z.ZodEnum<["1m", "5m", "15m", "1h", "4h", "1d"]>>>;
    strategies: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodEnum<["ema_crossover", "rsi_oversold", "macd_signal", "bollinger_bounce", "volume_breakout", "llm_sentiment", "combined"]>, "many">>>;
    maxDailyLossPct: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    cooldownAfterLossMinutes: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    autonomyLevel?: "full" | "guided" | "strict" | undefined;
    llmModel?: string | undefined;
    pairs?: string[] | undefined;
    description?: string | undefined;
    llmFallback?: string | undefined;
    maxLlmCallsPerHour?: number | undefined;
    chain?: "base" | undefined;
    dexes?: ("aerodrome" | "uniswap-v3")[] | undefined;
    paperBalance?: number | undefined;
    maxPositionSizePct?: number | undefined;
    maxOpenPositions?: number | undefined;
    stopLossPct?: number | undefined;
    takeProfitPct?: number | undefined;
    slippageSimulation?: number | undefined;
    analysisInterval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | undefined;
    strategies?: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[] | undefined;
    maxDailyLossPct?: number | undefined;
    cooldownAfterLossMinutes?: number | undefined;
}, {
    name?: string | undefined;
    autonomyLevel?: "full" | "guided" | "strict" | undefined;
    llmModel?: string | undefined;
    pairs?: string[] | undefined;
    description?: string | undefined;
    llmFallback?: string | undefined;
    maxLlmCallsPerHour?: number | undefined;
    chain?: "base" | undefined;
    dexes?: ("aerodrome" | "uniswap-v3")[] | undefined;
    paperBalance?: number | undefined;
    maxPositionSizePct?: number | undefined;
    maxOpenPositions?: number | undefined;
    stopLossPct?: number | undefined;
    takeProfitPct?: number | undefined;
    slippageSimulation?: number | undefined;
    analysisInterval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | undefined;
    strategies?: ("rsi_oversold" | "ema_crossover" | "macd_signal" | "bollinger_bounce" | "combined" | "volume_breakout" | "llm_sentiment")[] | undefined;
    maxDailyLossPct?: number | undefined;
    cooldownAfterLossMinutes?: number | undefined;
}>;
