import type { AgentBehaviorConfig } from '../validation.js';

export interface AgentProfile {
  id: string;
  name: string;
  description: string;
  emoji: string;
  category: 'preset' | 'custom';
  behavior: AgentBehaviorConfig;
}

export const AGENT_PROFILES: AgentProfile[] = [
  {
    id: 'diamond_hands',
    name: 'Diamond Hands',
    emoji: '💎',
    category: 'preset',
    description: 'Never sells early, high conviction holder. Patient, low panic sell, position style with long memory.',
    behavior: {
      riskAppetite: 'moderate',
      fomoProne: 10,
      panicSellThreshold: 5,
      contrarian: 30,
      analysisDepth: 'thorough',
      decisionSpeed: 'patient',
      confidenceThreshold: 75,
      overthinker: false,
      style: 'position',
      preferredConditions: 'trending',
      entryPreference: 'pullback',
      exitStrategy: 'signal_based',
      averageDown: true,
      verbosity: 'normal',
      personality: 'professional',
      emotionalAwareness: true,
      defaultBias: 'bullish',
      adaptability: 20,
      memoryWeight: 'long',
    },
  },
  {
    id: 'degen_ape',
    name: 'Degen Ape',
    emoji: '🦍',
    category: 'preset',
    description: 'YOLO momentum trader. Aggressive, high FOMO, impulsive scalper with meme lord personality.',
    behavior: {
      riskAppetite: 'degen',
      fomoProne: 90,
      panicSellThreshold: 20,
      contrarian: 10,
      analysisDepth: 'quick',
      decisionSpeed: 'impulsive',
      confidenceThreshold: 30,
      overthinker: false,
      style: 'scalper',
      preferredConditions: 'volatile',
      entryPreference: 'momentum',
      exitStrategy: 'trailing',
      averageDown: false,
      verbosity: 'stream_of_consciousness',
      personality: 'meme_lord',
      emotionalAwareness: true,
      defaultBias: 'bullish',
      adaptability: 90,
      memoryWeight: 'short',
    },
  },
  {
    id: 'the_professor',
    name: 'The Professor',
    emoji: '🎓',
    category: 'preset',
    description: 'Academic, data-driven, cautious. Thorough analysis, high confidence threshold, conservative.',
    behavior: {
      riskAppetite: 'conservative',
      fomoProne: 5,
      panicSellThreshold: 40,
      contrarian: 30,
      analysisDepth: 'thorough',
      decisionSpeed: 'patient',
      confidenceThreshold: 80,
      overthinker: true,
      style: 'swing',
      preferredConditions: 'trending',
      entryPreference: 'pullback',
      exitStrategy: 'signal_based',
      averageDown: false,
      verbosity: 'detailed',
      personality: 'academic',
      emotionalAwareness: false,
      defaultBias: 'neutral',
      adaptability: 30,
      memoryWeight: 'long',
    },
  },
  {
    id: 'whale_watcher',
    name: 'Whale Watcher',
    emoji: '🐋',
    category: 'preset',
    description: 'Follows smart money and big moves. Breakout entries, trending conditions, detailed logging.',
    behavior: {
      riskAppetite: 'moderate',
      fomoProne: 50,
      panicSellThreshold: 35,
      contrarian: 15,
      analysisDepth: 'balanced',
      decisionSpeed: 'measured',
      confidenceThreshold: 65,
      overthinker: false,
      style: 'swing',
      preferredConditions: 'trending',
      entryPreference: 'breakout',
      exitStrategy: 'trailing',
      averageDown: false,
      verbosity: 'detailed',
      personality: 'professional',
      emotionalAwareness: false,
      defaultBias: 'bullish',
      adaptability: 60,
      memoryWeight: 'medium',
    },
  },
  {
    id: 'scared_cat',
    name: 'Scared Cat',
    emoji: '🐱',
    category: 'preset',
    description: 'Extremely risk averse with tight stops. Conservative, high panic sell, minimal positions.',
    behavior: {
      riskAppetite: 'conservative',
      fomoProne: 5,
      panicSellThreshold: 90,
      contrarian: 10,
      analysisDepth: 'balanced',
      decisionSpeed: 'patient',
      confidenceThreshold: 85,
      overthinker: true,
      style: 'position',
      preferredConditions: 'ranging',
      entryPreference: 'pullback',
      exitStrategy: 'tight_stops',
      averageDown: false,
      verbosity: 'minimal',
      personality: 'professional',
      emotionalAwareness: true,
      defaultBias: 'neutral',
      adaptability: 20,
      memoryWeight: 'short',
    },
  },
  {
    id: 'contrarian_chad',
    name: 'Contrarian Chad',
    emoji: '🔄',
    category: 'preset',
    description: 'Always bets against the crowd. High contrarian, pullback/dip_buy entry, bearish default bias.',
    behavior: {
      riskAppetite: 'aggressive',
      fomoProne: 5,
      panicSellThreshold: 30,
      contrarian: 95,
      analysisDepth: 'balanced',
      decisionSpeed: 'measured',
      confidenceThreshold: 55,
      overthinker: false,
      style: 'swing',
      preferredConditions: 'volatile',
      entryPreference: 'dip_buy',
      exitStrategy: 'signal_based',
      averageDown: true,
      verbosity: 'normal',
      personality: 'casual',
      emotionalAwareness: false,
      defaultBias: 'bearish',
      adaptability: 40,
      memoryWeight: 'medium',
    },
  },
  {
    id: 'the_bot',
    name: 'The Bot',
    emoji: '🤖',
    category: 'preset',
    description: 'Pure signals, zero emotion. Strict analysis, no emotional awareness, signal-based exits.',
    behavior: {
      riskAppetite: 'moderate',
      fomoProne: 0,
      panicSellThreshold: 0,
      contrarian: 0,
      analysisDepth: 'balanced',
      decisionSpeed: 'measured',
      confidenceThreshold: 60,
      overthinker: false,
      style: 'hybrid',
      preferredConditions: 'any',
      entryPreference: 'momentum',
      exitStrategy: 'signal_based',
      averageDown: false,
      verbosity: 'normal',
      personality: 'professional',
      emotionalAwareness: false,
      defaultBias: 'neutral',
      adaptability: 50,
      memoryWeight: 'medium',
    },
  },
  {
    id: 'momentum_surfer',
    name: 'Momentum Surfer',
    emoji: '🏄',
    category: 'preset',
    description: 'Rides trends until they break. Aggressive on trends, trailing stops, high adaptability.',
    behavior: {
      riskAppetite: 'aggressive',
      fomoProne: 70,
      panicSellThreshold: 25,
      contrarian: 5,
      analysisDepth: 'quick',
      decisionSpeed: 'impulsive',
      confidenceThreshold: 45,
      overthinker: false,
      style: 'scalper',
      preferredConditions: 'trending',
      entryPreference: 'momentum',
      exitStrategy: 'trailing',
      averageDown: false,
      verbosity: 'normal',
      personality: 'casual',
      emotionalAwareness: true,
      defaultBias: 'bullish',
      adaptability: 85,
      memoryWeight: 'short',
    },
  },
  {
    id: 'the_sniper',
    name: 'The Sniper',
    emoji: '🎯',
    category: 'preset',
    description: 'Very few trades, very high conviction. Patient, very high confidence threshold, thorough.',
    behavior: {
      riskAppetite: 'conservative',
      fomoProne: 5,
      panicSellThreshold: 20,
      contrarian: 25,
      analysisDepth: 'thorough',
      decisionSpeed: 'patient',
      confidenceThreshold: 90,
      overthinker: false,
      style: 'position',
      preferredConditions: 'trending',
      entryPreference: 'breakout',
      exitStrategy: 'signal_based',
      averageDown: false,
      verbosity: 'detailed',
      personality: 'professional',
      emotionalAwareness: false,
      defaultBias: 'neutral',
      adaptability: 25,
      memoryWeight: 'long',
    },
  },
  {
    id: 'paper_hands',
    name: 'Paper Hands',
    emoji: '🧻',
    category: 'preset',
    description: 'Sells at the first sign of trouble. High panic sell, impulsive, tight stops, short memory.',
    behavior: {
      riskAppetite: 'conservative',
      fomoProne: 80,
      panicSellThreshold: 95,
      contrarian: 5,
      analysisDepth: 'quick',
      decisionSpeed: 'impulsive',
      confidenceThreshold: 25,
      overthinker: false,
      style: 'scalper',
      preferredConditions: 'any',
      entryPreference: 'momentum',
      exitStrategy: 'tight_stops',
      averageDown: false,
      verbosity: 'minimal',
      personality: 'casual',
      emotionalAwareness: true,
      defaultBias: 'neutral',
      adaptability: 70,
      memoryWeight: 'short',
    },
  },
];

export function getAgentProfile(id: string): AgentProfile | undefined {
  return AGENT_PROFILES.find((p) => p.id === id);
}

export const DEFAULT_AGENT_PROFILE_ID = 'the_bot';
